title: 大塚 sake walk 2022 マップ created PWAマップ Ver 2.0
description: Google スプレッドシートを更新するだけでオリジナルの地図アプリを作成できる「Geolonia PWAマップ」で、大塚 sake walk 2022のマップを作りました。
hosting_url: https://kai4den.github.io/ootsukasakewalk2022_v2/
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vSDuQ8L9bjnCdb7rVxYSvkkewjEfkIpu1Q_hfjuj-TA9mRlgtncsLuQwU35a5O9Ckhj6gdmydt9XN2L/pub?output=csv
